// Generated by Selenium IDE

import calculator.AditionPage;
import org.junit.Test;
import org.openqa.selenium.WebDriver;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class AditionTest {
  @Test
  public void verifyAdditionOfTwoNumbersWithOneDigit() {
    AditionPage aditionPage = new AditionPage();
    assertThat(aditionPage.addTwoNumbers(), is("3"));
  }
}
