// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MultiplicationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void multiplication() {
    // Test name: multiplication
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("https://www.calculadora.org/");
    // 2 | setWindowSize | 1050x740 |  | 
    driver.manage().window().setSize(new Dimension(1050, 740));
    // 3 | click | css=.keys > span:nth-child(1) |  | 
    driver.findElement(By.cssSelector(".keys > span:nth-child(1)")).click();
    // 4 | click | css=.operator:nth-child(16) |  | 
    driver.findElement(By.cssSelector(".operator:nth-child(16)")).click();
    // 5 | click | css=span:nth-child(5) |  | 
    driver.findElement(By.cssSelector("span:nth-child(5)")).click();
    // 6 | click | css=.eval |  | 
    driver.findElement(By.cssSelector(".eval")).click();
    // 7 | click | css=.screen |  | 
    driver.findElement(By.cssSelector(".screen")).click();
    // 8 | close |  |  | 
    driver.close();
  }
}
